"""Structured OpenCV geometry stages kept separate from legacy v20."""

from .confidence import (
    DEFAULT_STRUCTURED_GEOMETRY_VALIDATION_THRESHOLDS,
    STRUCTURED_GEOMETRY_CONFIDENCE_VERSION,
    BoardGeometryDisposition,
    BoardGeometryEvidence,
    BoardGeometryReasonCode,
    GeometryConfidenceComponents,
    StructuredGeometryValidationThresholds,
    evaluate_geometry_confidence,
)
from .configuration_v2 import (
    DEFAULT_STRUCTURED_GEOMETRY_CONFIG_V2,
    STRUCTURED_GEOMETRY_CONFIG_V2_VERSION,
    AdaptiveAnalysisPolicyV2,
    GameGeometryEvidenceProfileV2,
    GeometryCandidateDecisionV2,
    GeometryCandidateDisposition,
    GeometryConfigMaturity,
    GeometryConfigV2Error,
    GeometryEvidenceReasonV2,
    GeometryEvidenceThresholdsV2,
    GeometryEvidenceWeightsV2,
    StructuredGeometryConfigV2,
    StructuredGeometryEvidenceV2,
    evaluate_geometry_candidate_v2,
)
from .geometry_engine import (
    STRUCTURED_OPENCV_INDEPENDENT_BOARD_VERSION,
    STRUCTURED_SOURCE_GEOMETRY_VERSION,
    BoardGeometryResult,
    GeometryEngine,
    SourceGeometryResult,
    SourceGeometryStatus,
    StructuredOpenCvGeometryEngine,
    refine_initialized_source_geometry,
)
from .global_initialization import (
    STRUCTURED_GEOMETRY_ENGINE_ID,
    STRUCTURED_GEOMETRY_GLOBAL_INITIALIZATION_VERSION,
    ActiveSlotInitialization,
    GlobalInitializationMethod,
    GlobalInitializationResult,
    GlobalInitializationStatus,
    StructuredGeometryInitializationError,
    StructuredGeometryInitializationRequest,
    StructuredGeometryInitializationThresholds,
)
from .global_initialization import (
    StructuredOpenCvGeometryEngine as StructuredGeometryGlobalInitializer,
)
from .line_refinement import (
    DEFAULT_STRUCTURED_BOARD_LINE_THRESHOLDS,
    STRUCTURED_BOARD_LINE_REFINEMENT_VERSION,
    BoardLineRefinementResult,
    BoardLineRefiner,
    GridLineOrientation,
    RefinedGridLine,
    StructuredBoardLineRefinementError,
    StructuredBoardLineThresholds,
)

__all__ = [
    "STRUCTURED_GEOMETRY_ENGINE_ID",
    "STRUCTURED_GEOMETRY_CONFIG_V2_VERSION",
    "STRUCTURED_GEOMETRY_CONFIDENCE_VERSION",
    "STRUCTURED_GEOMETRY_GLOBAL_INITIALIZATION_VERSION",
    "STRUCTURED_OPENCV_INDEPENDENT_BOARD_VERSION",
    "STRUCTURED_SOURCE_GEOMETRY_VERSION",
    "STRUCTURED_BOARD_LINE_REFINEMENT_VERSION",
    "ActiveSlotInitialization",
    "AdaptiveAnalysisPolicyV2",
    "BoardGeometryDisposition",
    "BoardGeometryEvidence",
    "BoardGeometryReasonCode",
    "BoardGeometryResult",
    "BoardLineRefinementResult",
    "BoardLineRefiner",
    "DEFAULT_STRUCTURED_BOARD_LINE_THRESHOLDS",
    "DEFAULT_STRUCTURED_GEOMETRY_VALIDATION_THRESHOLDS",
    "GeometryConfidenceComponents",
    "GeometryCandidateDecisionV2",
    "GeometryCandidateDisposition",
    "GeometryConfigMaturity",
    "GeometryConfigV2Error",
    "GeometryEvidenceReasonV2",
    "GeometryEvidenceThresholdsV2",
    "GeometryEvidenceWeightsV2",
    "GeometryEngine",
    "GlobalInitializationMethod",
    "GlobalInitializationResult",
    "GlobalInitializationStatus",
    "GridLineOrientation",
    "RefinedGridLine",
    "SourceGeometryResult",
    "SourceGeometryStatus",
    "StructuredBoardLineRefinementError",
    "StructuredBoardLineThresholds",
    "StructuredGeometryGlobalInitializer",
    "StructuredGeometryConfigV2",
    "StructuredGeometryEvidenceV2",
    "StructuredGeometryInitializationError",
    "StructuredGeometryInitializationRequest",
    "StructuredGeometryInitializationThresholds",
    "StructuredGeometryValidationThresholds",
    "StructuredOpenCvGeometryEngine",
    "GameGeometryEvidenceProfileV2",
    "DEFAULT_STRUCTURED_GEOMETRY_CONFIG_V2",
    "refine_initialized_source_geometry",
    "evaluate_geometry_confidence",
    "evaluate_geometry_candidate_v2",
]
