"""Pure contracts for the independent semi-automatic image selection workflow."""

from .contracts import (
    SEMI_AUTOMATIC_SELECTION_CONTRACT_VERSION,
    SEMI_AUTOMATIC_SELECTION_FULL_RANGE_SIZE,
    SEMI_AUTOMATIC_SELECTION_RANGE_CONVENTION,
    RangeEvidenceGate,
    RangeEvidenceObservation,
    RangeEvidenceResult,
    RangeEvidenceStatus,
    SemiAutomaticSelectionDirection,
    SemiAutomaticSelectionError,
    SemiAutomaticSelectionRange,
    SemiAutomaticSelectionRangeStatus,
    SemiAutomaticSelectionRunStatus,
    SemiAutomaticSelectionSource,
    SemiAutomaticSequenceBounds,
    expected_ranges_fingerprint,
    fingerprint_sources,
    is_valid_run_status_transition,
)

__all__ = [
    "SEMI_AUTOMATIC_SELECTION_CONTRACT_VERSION",
    "SEMI_AUTOMATIC_SELECTION_FULL_RANGE_SIZE",
    "SEMI_AUTOMATIC_SELECTION_RANGE_CONVENTION",
    "RangeEvidenceGate",
    "RangeEvidenceObservation",
    "RangeEvidenceResult",
    "RangeEvidenceStatus",
    "SemiAutomaticSelectionDirection",
    "SemiAutomaticSelectionError",
    "SemiAutomaticSelectionRange",
    "SemiAutomaticSelectionRangeStatus",
    "SemiAutomaticSelectionRunStatus",
    "SemiAutomaticSelectionSource",
    "SemiAutomaticSequenceBounds",
    "expected_ranges_fingerprint",
    "fingerprint_sources",
    "is_valid_run_status_transition",
]
